# ALGORITMO NEURAL_NETWORK.MLPCLASSIFIER
## Classificador de perceptron de várias camadas

In [1]:
# IMPORTAR A BIBLIOTECAS
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [2]:
# DEFINIR QUE OUTRAS PESSOAS AO APLICAR ESSE MODELO TENHA OS MESMO RESULTADOS
np.random.seed(5)

In [3]:
# IMPORTAR O DADASET DISPONÍVEL NO SKLEARN PARA ESSE ESTUDO
iris = datasets.load_iris()
# MOSTRAR A BASE DE DADOS
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
# SEPARAR A VARIÁVEL DEPENDENTE E INDEPENDENTE
x = iris.data
y = iris.target

In [5]:
# CRIAR UMA VARIÁVEL COM 150 ÍNDICES 
sufind = np.arange(150)
# EMBARALHAR ESSES VALORES ALEATORIAMENTE
np.random.shuffle(sufind)

In [6]:
# OBS: O DATASET CONTEM UM TOTAL DE 150 LINHAS
# PEGAR AS 100 PRIMEIRAS ALEATÓRIAS PARA USAR NA SEPARAÇÃO DOS DADOS DE TREINAMENTO E TESTE
x_treino = x [sufind[ :100], :]
x_teste = x [sufind[100: ], :]
y_treino = y [sufind[ :100]]
y_teste = y [sufind[100: ]]

In [7]:
# CRIAR A INTELIGÊNCIA ARTIFICIAL, E PASSAR ALGUNS PARÂMETROS
CLF = MLPClassifier(solver='sgd', hidden_layer_sizes=(3, ), learning_rate_init=0.001, activation='logistic', max_iter=1500, random_state=1)

# 'sgd' ESTAMOS USANDO O STOCHASTIC GRADIENT DESCENT OU EM PORTUGUÊS DESCIDA DO GRADIENTE ESTOCÁSTICO
# hidden_layer_sizes, É A QUANTIDADE DE NEURÔNIOS NA CAMADA ESCONDIDA
# learning_rate_init, TAXA DE APRENDIZADO INICIAL
# activation, FUNÇÃO DE ATIVAÇÃO PARA A CAMADA OCULTA, 'logistic', FUNÇÃO SIGMÓIDE LOGÍSTICA
# max_iter, NÚMERO MÁXIMO DE ITERAÇÕES
# random_state, DETERMINA A GERAÇÃO DE NÚMEROS ALEATÓRIOS

In [8]:
# TREINAR O MODELO
CLF.fit(x_treino, y_treino)
# FAZER A PREVISÃO PASSANDO PARA O MODELO DADOS QUE ELE AINDA NÃO VIU
y_pred = CLF.predict_proba(x_teste)
# MOSTRAR 
y_pred

# MATRIZ COM 50 LINHAS E 3 COLUNAS

array([[0.33575634, 0.36835812, 0.29588554],
       [0.33548631, 0.36864954, 0.29586414],
       [0.35122121, 0.36904394, 0.27973485],
       [0.33697444, 0.36882278, 0.29420277],
       [0.33602975, 0.36913348, 0.29483677],
       [0.33627729, 0.36756619, 0.29615652],
       [0.35094561, 0.37070437, 0.27835003],
       [0.33330051, 0.3644752 , 0.30222429],
       [0.33358603, 0.36893428, 0.29747969],
       [0.32935894, 0.36579394, 0.30484712],
       [0.33499759, 0.37051422, 0.29448819],
       [0.33182086, 0.36837785, 0.2998013 ],
       [0.34611289, 0.37025724, 0.28362987],
       [0.35112211, 0.37206133, 0.27681656],
       [0.33424107, 0.36800431, 0.29775462],
       [0.32580629, 0.36493861, 0.3092551 ],
       [0.35293547, 0.36840277, 0.27866176],
       [0.33184214, 0.36456091, 0.30359695],
       [0.35146924, 0.36889247, 0.27963828],
       [0.34670705, 0.36834344, 0.28494951],
       [0.33214507, 0.36804956, 0.29980538],
       [0.33486982, 0.36853906, 0.29659112],
       [0.

In [9]:
# PROCURAR QUAL COLUNA TEM MAIOR PROBABILIDADE
y_aux = np.argmax(y_pred, 1)
# MOSTRAR A PORCENTAGEM DE ACERTO DO MODELO
accuracy_score(y_teste, y_aux)
# OBS: ACURÁCIA FOI MUITO BAIXA, OBJETIVO MELHORAR ESSA MÉTRICA

0.28

In [10]:
# NÚMEROS NÃO ESTÃO NORMALIZADOS
x_treino

array([[5.8, 2.7, 3.9, 1.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.8, 2.8, 5.1, 2.4],
       [4.4, 3.2, 1.3, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 3. , 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.8, 5.1, 1.5],
       [7.1, 3. , 5.9, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [6.3, 2.7, 4.9, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.7, 1.5, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [6.1, 2.8, 4. , 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [6.2, 3.4, 5.4, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [6.1, 2.9, 4.7, 1.4],
       [6.4, 2.8, 5.6, 2.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.4, 3.7, 1.5, 0.2],
       [7. , 3

# NORMALIZANDO OS DADOS

In [11]:
# IMPORTO O MODELO PADRÃO DE NORMALIZAÇÃO
scaler = StandardScaler()

np.random.seed(5)
iris = datasets.load_iris()
x = iris.data
y = iris.target
# TREINAR 
scaler.fit(x)
# FAZER A NORMALIZAÇÃO DOS DADOS
x = scaler.transform(x)

sufind = np.arange(150)
np.random.shuffle(sufind)
x_treino = x [sufind[ :100], :]
x_teste = x [sufind[100: ], :]

y_treino = y [sufind[ :100]]
y_teste = y [sufind[100: ]]
CLF = MLPClassifier(solver='sgd', hidden_layer_sizes=(3, ), learning_rate_init=0.001, activation='logistic', max_iter=1500, random_state=1)
CLF.fit(x_treino, y_treino)
y_pred = CLF.predict_proba(x_teste)
y_aux = np.argmax(y_pred, 1)
# MOSTRAR A ACURÁCIA NOVAMENTE
accuracy_score(y_teste, y_aux)

# OBS: COM A NORMALIZAÇÃO MELHOROU E MUITO A ACURÁCIA DO MODELO PARA 86%

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.86

In [12]:
# MOSTRAR A TRANSFORMAÇÃO DO X DE TREINO
x_treino

array([[-5.25060772e-02, -8.22569778e-01,  8.07091462e-02,
         8.77547895e-04],
       [ 3.10997534e-01, -1.05276654e+00,  1.04694540e+00,
         2.64141916e-01],
       [-5.25060772e-02, -5.92373012e-01,  7.62758269e-01,
         1.58046376e+00],
       [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [ 1.64384411e+00,  1.24920112e+00,  1.33113254e+00,
         1.71209594e+00],
       [-1.14301691e+00, -1.51316008e+00, -2.60315415e-01,
        -2.62386821e-01],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [ 6.86617933e-02,  3.28414053e-01,  5.92245988e-01,
         7.90670654e-01],
       [-1.02184904e+00, -1.31979479e-01, -1.22655167e+00,
        -1.31544430e+00],
       [-5.37177559e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [-2.94841818e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [ 5.53333275e-01, -5.92373012e-01,  7.62758269e-01,
      

# AUMENTAR A TAXA DE APRENDIZADO USANDO NOVOS PARÂMETROS

In [13]:
scaler = StandardScaler()

np.random.seed(5)
iris = datasets.load_iris()
x = iris.data
y = iris.target

scaler.fit(x)
x = scaler.transform(x)

sufind = np.arange(150)
np.random.shuffle(sufind)
x_treino = x [sufind[ :100], :]
x_teste = x [sufind[100: ], :]

y_treino = y [sufind[ :100]]
y_teste = y [sufind[100: ]]

# FAZER UMAS MODIFICAÇÕES NOS PARÂMETROS PARA MELHORAR O MODELO AINDA MAIS
# MODIFICAR A TAXA DE APRENDIZADO INICIAL DE '0.001', PARA '0.01'.
CLF = MLPClassifier(solver='sgd', hidden_layer_sizes=(3, ), learning_rate_init=0.01, activation='logistic', max_iter=1500, random_state=1)
CLF.fit(x_treino, y_treino)
y_pred = CLF.predict_proba(x_teste)
y_aux = np.argmax(y_pred, 1)
accuracy_score(y_teste, y_aux)
# COM ESSE AJUSTE NO MODELO A ACURÁCIA ATINGE SEU MÁXIMO DE 98% E ATINGE SEU LIMITE.

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.98

In [14]:
# MOSTRAR OS 10 PRIMEIROS RESULTADOS PREVISTOS PELO MODELO
print(y_teste[:10], y_aux[:10])

[1 1 0 1 2 1 0 1 2 2] [1 1 0 1 2 1 0 1 2 2]
